// <auto-generated />
using System;
using ExpenseTrackerWebAPI_Mk2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseTrackerWebAPI_Mk2.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpenseTrackerWebAPI_Mk2.Models.Bank", b =>
                {
                    b.Property<Guid>("BankID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AccNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BankID");

                    b.HasIndex("AccNumber")
                        .IsUnique();

                    b.HasIndex("BankName")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            BankID = new Guid("795fcc24-1975-454c-86ac-0cc0db1e78c6"),
                            AccNumber = "122104569335",
                            Balance = 22381.200000000001,
                            BankName = "JP Morgan & Chase",
                            Status = false,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            BankID = new Guid("4d46c466-805b-4b9d-9dc3-a636ac913ee3"),
                            AccNumber = "117856353077",
                            Balance = 95555.5,
                            BankName = "Bank of America",
                            Status = false,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        });
                });

            modelBuilder.Entity("ExpenseTrackerWebAPI_Mk2.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("CategoryID");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = new Guid("f5186c55-332a-4eae-b917-7f5fae0b2a7b"),
                            CategoryName = "Entertainment",
                            Status = false
                        },
                        new
                        {
                            CategoryID = new Guid("a6d314d6-ab99-47f9-9b17-2c94f9f03086"),
                            CategoryName = "Travel",
                            Status = false
                        },
                        new
                        {
                            CategoryID = new Guid("4d627443-1ae0-49e0-8bf9-b1ea4b8cd8e1"),
                            CategoryName = "Clothing",
                            Status = false
                        },
                        new
                        {
                            CategoryID = new Guid("9ad4ccf1-f72b-4fe2-9c76-e91cd01445d8"),
                            CategoryName = "Dining",
                            Status = false
                        },
                        new
                        {
                            CategoryID = new Guid("8815ac70-1c20-4167-a045-964d819e195f"),
                            CategoryName = "Groceries",
                            Status = false
                        },
                        new
                        {
                            CategoryID = new Guid("b72e8dc1-1bc0-4b1e-b086-e412ed4a9dc0"),
                            CategoryName = "Healthcare",
                            Status = false
                        },
                        new
                        {
                            CategoryID = new Guid("a5c6d659-aaf2-495f-affc-015627059750"),
                            CategoryName = "Electronics",
                            Status = false
                        },
                        new
                        {
                            CategoryID = new Guid("43a9d80e-581d-4639-9bcd-e062e7ac7176"),
                            CategoryName = "Shopping",
                            Status = false
                        });
                });

            modelBuilder.Entity("ExpenseTrackerWebAPI_Mk2.Models.CreditCard", b =>
                {
                    b.Property<Guid>("CreditCardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CVC")
                        .HasColumnType("int");

                    b.Property<string>("CardHolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CreditLimit")
                        .HasColumnType("float");

                    b.Property<DateTime>("ExpDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("First4Digits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last4Digits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Network")
                        .HasColumnType("int");

                    b.Property<int>("PaymentDueIn")
                        .HasColumnType("int");

                    b.Property<string>("Second4Digits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatementGenDay")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Third4Digits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CreditCardID");

                    b.HasIndex("UserID");

                    b.ToTable("CreditCards", t =>
                        {
                            t.HasCheckConstraint("CHK_PaymentDueIn", "PaymentDueIn <= 31 AND PaymentDueIn >=1");

                            t.HasCheckConstraint("CHK_StatementGenDay", "StatementGenDay <= 31 AND StatementGenDay >=1");
                        });

                    b.HasData(
                        new
                        {
                            CreditCardID = new Guid("75987053-7057-499b-bdf6-14ac41509853"),
                            BankName = "CitiBank",
                            CVC = 127,
                            CardHolderName = "Admin Nim",
                            CardName = "CitiBank 1 7 8 0",
                            CreditLimit = 15000.0,
                            ExpDate = new DateTime(2032, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            First4Digits = "3 5 1 2",
                            Last4Digits = "1 7 8 0",
                            Network = 3,
                            PaymentDueIn = 20,
                            Second4Digits = "0 0 3 2",
                            StatementGenDay = 16,
                            Status = false,
                            Third4Digits = "3 7 6 9",
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            BankName = "Bank of America",
                            CVC = 435,
                            CardHolderName = "Admin Nim",
                            CardName = "Card 1",
                            CreditLimit = 75000.0,
                            ExpDate = new DateTime(2030, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            First4Digits = "5 4 3 2",
                            Last4Digits = "6 6 4 2",
                            Network = 1,
                            PaymentDueIn = 20,
                            Second4Digits = "1 2 9 9",
                            StatementGenDay = 21,
                            Status = false,
                            Third4Digits = "0 5 9 1",
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            BankName = "JP Morgan & Chase",
                            CVC = 380,
                            CardHolderName = "Admin Nim",
                            CardName = "Card 2",
                            CreditLimit = 15000.0,
                            ExpDate = new DateTime(2028, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            First4Digits = "9 8 7 6",
                            Last4Digits = "5 3 1 2",
                            Network = 0,
                            PaymentDueIn = 25,
                            Second4Digits = "4 3 2 7",
                            StatementGenDay = 15,
                            Status = false,
                            Third4Digits = "9 7 5 2",
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        });
                });

            modelBuilder.Entity("ExpenseTrackerWebAPI_Mk2.Models.Recipient", b =>
                {
                    b.Property<Guid>("RecipientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("RecipientID");

                    b.HasIndex("RecipientName")
                        .IsUnique();

                    b.ToTable("Recipients");

                    b.HasData(
                        new
                        {
                            RecipientID = new Guid("fec14558-524a-46a1-ab0e-f8acfaf9ab49"),
                            RecipientName = "H&M",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("3cfff9f1-d8b3-4396-a44f-622899681719"),
                            RecipientName = "Ralph Lauren",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("2b32e737-6637-47b2-b150-ca3af794d620"),
                            RecipientName = "Michael Kors",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("dc769f30-ba3c-4df8-8e9e-44d0f905dea6"),
                            RecipientName = "OLD NAVY",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("b7caea13-1d1a-4780-831a-ed973765c67a"),
                            RecipientName = "Gap Inc",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("04848095-f6d3-489e-bfd2-92b09e039019"),
                            RecipientName = "Burger King",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("5d47a329-4a2d-4676-b349-3d26958ff25d"),
                            RecipientName = "McDonald's",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("41f99a2a-3fed-4bec-bee2-465f46f933a5"),
                            RecipientName = "Chick-fil-A",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("6ecf6c47-660e-4871-a6fc-9c17167a3b5d"),
                            RecipientName = "Panda Express",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("1a45beda-0d80-4ddc-9ba7-c12da07e7ab7"),
                            RecipientName = "Insomnia Cookies",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("dea8e720-e79c-4fc3-81fd-201befa9f904"),
                            RecipientName = "Dunkin' Donuts",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("cd39920e-7b14-4043-be69-2ebab1a7cd3e"),
                            RecipientName = "Dutch Bros. Coffee",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("7bb90da3-fee4-4a5b-8679-5d820e90ac3d"),
                            RecipientName = "Burlington",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("c7ee15e0-5480-4544-b2d6-094ba5134ac7"),
                            RecipientName = "Costco",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("1059d5f9-e4aa-4c06-8f35-e664b6215378"),
                            RecipientName = "Walmart",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("18884556-def7-499c-89df-09a8d95b62d0"),
                            RecipientName = "Target",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("1b5a7d64-2e25-48cd-8cd6-9587f6078ca5"),
                            RecipientName = "BestBuy",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("a53c4426-df1c-4325-8e52-4ea027a6e83e"),
                            RecipientName = "Kroger",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("dfb07eb1-81e9-4139-8419-ba545f0db07a"),
                            RecipientName = "H-E-B",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("3ebaa280-3ec4-4b68-aa21-f9b2fe2cbd63"),
                            RecipientName = "CVS",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("73f04239-ca28-47e1-9243-a8c888c06f4c"),
                            RecipientName = "American Airlines",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("7431dc59-2e5a-4863-a58b-05e17566e310"),
                            RecipientName = "Delta",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("03a5b5de-e9ec-4e70-94f2-00da5d667787"),
                            RecipientName = "United",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("df7269a9-6c65-434f-bcd5-d9853b0b75b3"),
                            RecipientName = "Air France",
                            Status = false
                        },
                        new
                        {
                            RecipientID = new Guid("4575e719-3887-413b-9b30-326cf11d27f7"),
                            RecipientName = "Southwest",
                            Status = false
                        });
                });

            modelBuilder.Entity("ExpenseTrackerWebAPI_Mk2.Models.Transaction", b =>
                {
                    b.Property<Guid>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<Guid?>("BankID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreditCardID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneralComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentMode")
                        .HasColumnType("int");

                    b.Property<Guid>("RecipientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RewardPoints")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("TransactionMode")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TransactionID");

                    b.HasIndex("BankID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("CreditCardID");

                    b.HasIndex("RecipientID");

                    b.HasIndex("UserID");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionID = new Guid("1a9b89a2-da14-4eca-bf84-8bfa6dad823a"),
                            Amount = 100.0,
                            CategoryID = new Guid("8815ac70-1c20-4167-a045-964d819e195f"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Purchased groceries for the week at Costco.",
                            PaymentMode = 1,
                            RecipientID = new Guid("c7ee15e0-5480-4544-b2d6-094ba5134ac7"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("3f3d54d9-2a94-48d4-a97c-fa8c31c57f02"),
                            Amount = 100.0,
                            CategoryID = new Guid("43a9d80e-581d-4639-9bcd-e062e7ac7176"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Purchased winter accessories from Burlington.",
                            PaymentMode = 1,
                            RecipientID = new Guid("7bb90da3-fee4-4a5b-8679-5d820e90ac3d"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("9a1e55bb-080d-414d-bd88-f70c8c87fa6b"),
                            Amount = 220.0,
                            CategoryID = new Guid("a6d314d6-ab99-47f9-9b17-2c94f9f03086"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2023, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Booked a round-trip ticket with Southwest.",
                            PaymentMode = 1,
                            RecipientID = new Guid("4575e719-3887-413b-9b30-326cf11d27f7"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("2b4c0db2-156b-4d56-85bc-2344b481d263"),
                            Amount = 75.0,
                            CategoryID = new Guid("8815ac70-1c20-4167-a045-964d819e195f"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2023, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Stocked up on essentials from Kroger.",
                            PaymentMode = 1,
                            RecipientID = new Guid("a53c4426-df1c-4325-8e52-4ea027a6e83e"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("3d56bf6a-7d6f-4eae-8b92-788ad83eca3e"),
                            Amount = 25.0,
                            CategoryID = new Guid("9ad4ccf1-f72b-4fe2-9c76-e91cd01445d8"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2023, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Enjoyed a quick lunch at Burger King.",
                            PaymentMode = 1,
                            RecipientID = new Guid("04848095-f6d3-489e-bfd2-92b09e039019"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("8a49e1ed-5243-4b8b-bf3b-ca622953c63d"),
                            Amount = 200.0,
                            CategoryID = new Guid("a5c6d659-aaf2-495f-affc-015627059750"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2023, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Bought a new tablet for reading and entertainment.",
                            PaymentMode = 1,
                            RecipientID = new Guid("1059d5f9-e4aa-4c06-8f35-e664b6215378"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("5e8e09a6-f6d0-44a3-9621-8f59f4c30534"),
                            Amount = 35.0,
                            CategoryID = new Guid("9ad4ccf1-f72b-4fe2-9c76-e91cd01445d8"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2023, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Enjoyed a family dinner at Chick-fil-A.",
                            PaymentMode = 1,
                            RecipientID = new Guid("41f99a2a-3fed-4bec-bee2-465f46f933a5"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("7e1d5e54-fb92-4b3f-a356-1ebfe67fc1e7"),
                            Amount = 30.0,
                            CategoryID = new Guid("9ad4ccf1-f72b-4fe2-9c76-e91cd01445d8"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2023, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Enjoyed a quick meal at Panda Express.",
                            PaymentMode = 1,
                            RecipientID = new Guid("6ecf6c47-660e-4871-a6fc-9c17167a3b5d"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("8afa5455-fdf1-4e93-8e77-be663b175a6e"),
                            Amount = 80.0,
                            CategoryID = new Guid("43a9d80e-581d-4639-9bcd-e062e7ac7176"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2023, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Purchased winter clothing at H&M.",
                            PaymentMode = 1,
                            RecipientID = new Guid("fec14558-524a-46a1-ab0e-f8acfaf9ab49"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("5e1a58c8-40bc-47e6-baa4-3b5b6a20509e"),
                            Amount = 300.0,
                            CategoryID = new Guid("a5c6d659-aaf2-495f-affc-015627059750"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Purchased a new smartphone from BestBuy.",
                            PaymentMode = 1,
                            RecipientID = new Guid("1b5a7d64-2e25-48cd-8cd6-9587f6078ca5"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("1d07b74a-732e-4721-adce-f4c7c4a5a125"),
                            Amount = 350.0,
                            CategoryID = new Guid("a6d314d6-ab99-47f9-9b17-2c94f9f03086"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Booked a round-trip flight with United Airlines.",
                            PaymentMode = 1,
                            RecipientID = new Guid("03a5b5de-e9ec-4e70-94f2-00da5d667787"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("2c7d40db-86a5-4698-8cc3-ffc79a64e572"),
                            Amount = 400.0,
                            CategoryID = new Guid("a5c6d659-aaf2-495f-affc-015627059750"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Bought a gaming console from BestBuy.",
                            PaymentMode = 1,
                            RecipientID = new Guid("1b5a7d64-2e25-48cd-8cd6-9587f6078ca5"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("2d62b49a-92a3-43bc-9628-ebf167d31c8f"),
                            Amount = 55.0,
                            CategoryID = new Guid("43a9d80e-581d-4639-9bcd-e062e7ac7176"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2023, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Purchased a new sweater from Gap.",
                            PaymentMode = 1,
                            RecipientID = new Guid("b7caea13-1d1a-4780-831a-ed973765c67a"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("4f3a197b-bf8b-4745-94cc-6c1b0d1c8baf"),
                            Amount = 50.0,
                            CategoryID = new Guid("9ad4ccf1-f72b-4fe2-9c76-e91cd01445d8"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Enjoyed snacks during a Delta flight.",
                            PaymentMode = 1,
                            RecipientID = new Guid("7431dc59-2e5a-4863-a58b-05e17566e310"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("62b2c92b-9c07-4878-bb03-8e6010d653e8"),
                            Amount = 120.0,
                            CategoryID = new Guid("8815ac70-1c20-4167-a045-964d819e195f"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2023, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Bought bulk groceries from Costco.",
                            PaymentMode = 1,
                            RecipientID = new Guid("c7ee15e0-5480-4544-b2d6-094ba5134ac7"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("6f4f7b9c-5d96-466d-83a5-b9d77b35c4e1"),
                            Amount = 50.0,
                            CategoryID = new Guid("8815ac70-1c20-4167-a045-964d819e195f"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2023, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Stocked up on snacks and drinks at Kroger.",
                            PaymentMode = 1,
                            RecipientID = new Guid("a53c4426-df1c-4325-8e52-4ea027a6e83e"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("1c02bc7e-f204-4e8f-bae2-f8d24bc8d401"),
                            Amount = 500.0,
                            CategoryID = new Guid("a6d314d6-ab99-47f9-9b17-2c94f9f03086"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2023, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Purchased a flight ticket with American Airlines.",
                            PaymentMode = 1,
                            RecipientID = new Guid("73f04239-ca28-47e1-9243-a8c888c06f4c"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("4f493f8c-5a80-493a-8f24-ec1d0897c3a3"),
                            Amount = 70.0,
                            CategoryID = new Guid("f5186c55-332a-4eae-b917-7f5fae0b2a7b"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2023, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Enjoyed in-flight entertainment on American Airlines.",
                            PaymentMode = 1,
                            RecipientID = new Guid("73f04239-ca28-47e1-9243-a8c888c06f4c"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("2a15a4ed-134a-4268-9133-b28ff8c46a04"),
                            Amount = 75.0,
                            CategoryID = new Guid("43a9d80e-581d-4639-9bcd-e062e7ac7176"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2023, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Bought holiday gifts at Target.",
                            PaymentMode = 1,
                            RecipientID = new Guid("18884556-def7-499c-89df-09a8d95b62d0"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("7b7f48f6-9a35-411c-b3eb-ee79d96c4f66"),
                            Amount = 20.0,
                            CategoryID = new Guid("9ad4ccf1-f72b-4fe2-9c76-e91cd01445d8"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2023, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Grabbed breakfast from Dunkin' Donuts.",
                            PaymentMode = 1,
                            RecipientID = new Guid("dea8e720-e79c-4fc3-81fd-201befa9f904"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("5c8c8ff9-d91c-4d99-a126-36a098bec1b4"),
                            Amount = 30.0,
                            CategoryID = new Guid("9ad4ccf1-f72b-4fe2-9c76-e91cd01445d8"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2023, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Had dinner at Chick-fil-A with family.",
                            PaymentMode = 1,
                            RecipientID = new Guid("41f99a2a-3fed-4bec-bee2-465f46f933a5"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("3a4b28d4-2b71-42b9-a89e-13da1d10d9d6"),
                            Amount = 25.0,
                            CategoryID = new Guid("9ad4ccf1-f72b-4fe2-9c76-e91cd01445d8"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2023, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Had a late-night snack at Burger King.",
                            PaymentMode = 1,
                            RecipientID = new Guid("04848095-f6d3-489e-bfd2-92b09e039019"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("1e7dba55-d7a2-485e-b87b-64b98c7fa2c5"),
                            Amount = 200.0,
                            CategoryID = new Guid("a5c6d659-aaf2-495f-affc-015627059750"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2023, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Purchased a tablet as a holiday gift.",
                            PaymentMode = 1,
                            RecipientID = new Guid("1059d5f9-e4aa-4c06-8f35-e664b6215378"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("6e7a7335-7e63-4e06-bc4b-36f8586bb4c4"),
                            Amount = 500.0,
                            CategoryID = new Guid("a6d314d6-ab99-47f9-9b17-2c94f9f03086"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2023, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Purchased a last-minute ticket for Delta Airlines.",
                            PaymentMode = 1,
                            RecipientID = new Guid("7431dc59-2e5a-4863-a58b-05e17566e310"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("4d7e41f9-505c-431e-af61-32c84e07df6b"),
                            Amount = 150.0,
                            CategoryID = new Guid("f5186c55-332a-4eae-b917-7f5fae0b2a7b"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2023, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Purchased tickets for a trip with Delta.",
                            PaymentMode = 1,
                            RecipientID = new Guid("7431dc59-2e5a-4863-a58b-05e17566e310"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("6f100d66-fc30-4fa2-be71-cb62f16120b4"),
                            Amount = 150.0,
                            CategoryID = new Guid("f5186c55-332a-4eae-b917-7f5fae0b2a7b"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2023, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Attended a fashion show featuring Ralph Lauren.",
                            PaymentMode = 1,
                            RecipientID = new Guid("3cfff9f1-d8b3-4396-a44f-622899681719"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("4a0e6c4d-6edb-43a6-877c-b9c96d1cda92"),
                            Amount = 300.0,
                            CategoryID = new Guid("a5c6d659-aaf2-495f-affc-015627059750"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2023, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Bought a new laptop from BestBuy for work.",
                            PaymentMode = 1,
                            RecipientID = new Guid("1b5a7d64-2e25-48cd-8cd6-9587f6078ca5"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("3f35a59a-f20d-465c-8f6f-32bb0fffb56d"),
                            Amount = 350.0,
                            CategoryID = new Guid("a6d314d6-ab99-47f9-9b17-2c94f9f03086"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2023, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Booked a flight with American Airlines for vacation.",
                            PaymentMode = 1,
                            RecipientID = new Guid("73f04239-ca28-47e1-9243-a8c888c06f4c"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("2e8f06a1-6a58-429e-9b75-0f0191a57d91"),
                            Amount = 600.0,
                            CategoryID = new Guid("a6d314d6-ab99-47f9-9b17-2c94f9f03086"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Booked a round-trip flight for a business trip.",
                            PaymentMode = 1,
                            RecipientID = new Guid("03a5b5de-e9ec-4e70-94f2-00da5d667787"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("7a67d568-c099-4e61-b067-8d16c891fa68"),
                            Amount = 65.0,
                            CategoryID = new Guid("43a9d80e-581d-4639-9bcd-e062e7ac7176"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Purchased winter clothing from Burlington.",
                            PaymentMode = 1,
                            RecipientID = new Guid("7bb90da3-fee4-4a5b-8679-5d820e90ac3d"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("4c3c5d6c-2736-44d4-9d77-180a7bb7e10c"),
                            Amount = 28.0,
                            CategoryID = new Guid("9ad4ccf1-f72b-4fe2-9c76-e91cd01445d8"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Had a meal at Panda Express after shopping.",
                            PaymentMode = 1,
                            RecipientID = new Guid("6ecf6c47-660e-4871-a6fc-9c17167a3b5d"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("3d6784c2-612a-4420-8d38-354f1d4b199c"),
                            Amount = 25.0,
                            CategoryID = new Guid("9ad4ccf1-f72b-4fe2-9c76-e91cd01445d8"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Enjoyed a coffee and pastry at Dunkin' Donuts.",
                            PaymentMode = 1,
                            RecipientID = new Guid("dea8e720-e79c-4fc3-81fd-201befa9f904"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("4f97f8c3-f33e-4d35-912d-ca4c73f39f56"),
                            Amount = 12.0,
                            CategoryID = new Guid("f5186c55-332a-4eae-b917-7f5fae0b2a7b"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Watched a movie on the flight with American Airlines.",
                            PaymentMode = 1,
                            RecipientID = new Guid("73f04239-ca28-47e1-9243-a8c888c06f4c"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("5a1d5b77-eb9a-447d-a2b9-4f7d4e82f063"),
                            Amount = 150.0,
                            CategoryID = new Guid("f5186c55-332a-4eae-b917-7f5fae0b2a7b"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Attended a fashion event featuring Ralph Lauren.",
                            PaymentMode = 1,
                            RecipientID = new Guid("3cfff9f1-d8b3-4396-a44f-622899681719"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("63ba5b48-fb89-4dbd-b40d-b55b14eb5dd7"),
                            Amount = 499.0,
                            CategoryID = new Guid("a5c6d659-aaf2-495f-affc-015627059750"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Bought a new smartphone at BestBuy.",
                            PaymentMode = 1,
                            RecipientID = new Guid("1b5a7d64-2e25-48cd-8cd6-9587f6078ca5"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("1f12b98e-9c29-4c41-8586-ad340a3565f9"),
                            Amount = 70.0,
                            CategoryID = new Guid("43a9d80e-581d-4639-9bcd-e062e7ac7176"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Purchased some new jeans at Gap.",
                            PaymentMode = 1,
                            RecipientID = new Guid("b7caea13-1d1a-4780-831a-ed973765c67a"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("6e2f5b73-4d75-43a4-8a80-07c20544d154"),
                            Amount = 250.0,
                            CategoryID = new Guid("a6d314d6-ab99-47f9-9b17-2c94f9f03086"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Booked a flight with Delta Airlines for vacation.",
                            PaymentMode = 1,
                            RecipientID = new Guid("7431dc59-2e5a-4863-a58b-05e17566e310"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("6d23e27c-477d-4c77-b69f-8d8ed593d5c9"),
                            Amount = 250.0,
                            CategoryID = new Guid("a5c6d659-aaf2-495f-affc-015627059750"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Bought a smart home device from BestBuy.",
                            PaymentMode = 1,
                            RecipientID = new Guid("1b5a7d64-2e25-48cd-8cd6-9587f6078ca5"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("5a8b6b9b-d8e0-49c1-ac58-bde963635df4"),
                            Amount = 110.0,
                            CategoryID = new Guid("8815ac70-1c20-4167-a045-964d819e195f"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Did monthly shopping at Costco.",
                            PaymentMode = 1,
                            RecipientID = new Guid("c7ee15e0-5480-4544-b2d6-094ba5134ac7"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("4eaa2b7c-4b58-41c3-9e4b-3a9dbe73f19a"),
                            Amount = 45.0,
                            CategoryID = new Guid("43a9d80e-581d-4639-9bcd-e062e7ac7176"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Bought a new jacket from H&M.",
                            PaymentMode = 1,
                            RecipientID = new Guid("fec14558-524a-46a1-ab0e-f8acfaf9ab49"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("3d7bae39-2344-4a77-bd3f-c99c320d9e3c"),
                            Amount = 700.0,
                            CategoryID = new Guid("a6d314d6-ab99-47f9-9b17-2c94f9f03086"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Purchased a flight ticket for a vacation.",
                            PaymentMode = 1,
                            RecipientID = new Guid("73f04239-ca28-47e1-9243-a8c888c06f4c"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("9d9f14d1-250e-40ed-8d42-02bb85fa72f6"),
                            Amount = 35.0,
                            CategoryID = new Guid("9ad4ccf1-f72b-4fe2-9c76-e91cd01445d8"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2024, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Enjoyed a family dinner at Chick-fil-A.",
                            PaymentMode = 1,
                            RecipientID = new Guid("41f99a2a-3fed-4bec-bee2-465f46f933a5"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("81a012a5-f90a-4c3b-88da-1b743a59cc4e"),
                            Amount = 40.0,
                            CategoryID = new Guid("9ad4ccf1-f72b-4fe2-9c76-e91cd01445d8"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Had a family lunch at Chick-fil-A.",
                            PaymentMode = 1,
                            RecipientID = new Guid("41f99a2a-3fed-4bec-bee2-465f46f933a5"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("c92a1d1d-22fc-408c-bda6-98bc62330e08"),
                            Amount = 250.0,
                            CategoryID = new Guid("a5c6d659-aaf2-495f-affc-015627059750"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Purchased a new TV from Walmart.",
                            PaymentMode = 1,
                            RecipientID = new Guid("1059d5f9-e4aa-4c06-8f35-e664b6215378"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("4a8c0043-0fae-42ac-b4a3-fa6b3c5d60e5"),
                            Amount = 110.0,
                            CategoryID = new Guid("8815ac70-1c20-4167-a045-964d819e195f"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Stocked up on groceries at Costco.",
                            PaymentMode = 1,
                            RecipientID = new Guid("c7ee15e0-5480-4544-b2d6-094ba5134ac7"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("38e4e39a-4b82-44ed-b90b-563f5c2e6f45"),
                            Amount = 700.0,
                            CategoryID = new Guid("a6d314d6-ab99-47f9-9b17-2c94f9f03086"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Bought a last-minute flight ticket for travel.",
                            PaymentMode = 1,
                            RecipientID = new Guid("73f04239-ca28-47e1-9243-a8c888c06f4c"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("2eed2e7e-8858-491f-aff4-67c1a3130d02"),
                            Amount = 80.0,
                            CategoryID = new Guid("a5c6d659-aaf2-495f-affc-015627059750"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Purchased kitchen appliances from Walmart.",
                            PaymentMode = 1,
                            RecipientID = new Guid("1059d5f9-e4aa-4c06-8f35-e664b6215378"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("6b4d03f4-3e5a-4324-8f9e-1a5b92980f53"),
                            Amount = 900.0,
                            CategoryID = new Guid("a6d314d6-ab99-47f9-9b17-2c94f9f03086"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Booked a flight to Paris with Air France.",
                            PaymentMode = 1,
                            RecipientID = new Guid("df7269a9-6c65-434f-bcd5-d9853b0b75b3"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("9d05b8e3-5b65-4703-85f1-bd9c32c60091"),
                            Amount = 850.0,
                            CategoryID = new Guid("a6d314d6-ab99-47f9-9b17-2c94f9f03086"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Round-trip flight to London on United Airlines.",
                            PaymentMode = 1,
                            RecipientID = new Guid("03a5b5de-e9ec-4e70-94f2-00da5d667787"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("1cbef37d-1b75-4bfd-97a9-9c8e468f0c78"),
                            Amount = 80.0,
                            CategoryID = new Guid("43a9d80e-581d-4639-9bcd-e062e7ac7176"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Purchased souvenirs at Gap before the trip.",
                            PaymentMode = 1,
                            RecipientID = new Guid("b7caea13-1d1a-4780-831a-ed973765c67a"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("4f8a19f6-b4d1-4a0f-bda3-8f073b6538bc"),
                            Amount = 700.0,
                            CategoryID = new Guid("a6d314d6-ab99-47f9-9b17-2c94f9f03086"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Booked a flight to Barcelona with Delta Airlines.",
                            PaymentMode = 1,
                            RecipientID = new Guid("7431dc59-2e5a-4863-a58b-05e17566e310"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("8fc6d79e-c2a6-4f56-a05d-0fca4b0bfbc5"),
                            Amount = 300.0,
                            CategoryID = new Guid("a5c6d659-aaf2-495f-affc-015627059750"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Bought a travel adapter at BestBuy.",
                            PaymentMode = 1,
                            RecipientID = new Guid("1b5a7d64-2e25-48cd-8cd6-9587f6078ca5"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("7d8b8c6a-3f40-4908-b25b-db4a97e8f17e"),
                            Amount = 950.0,
                            CategoryID = new Guid("a6d314d6-ab99-47f9-9b17-2c94f9f03086"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2024, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Booked a last-minute flight to Tokyo.",
                            PaymentMode = 1,
                            RecipientID = new Guid("73f04239-ca28-47e1-9243-a8c888c06f4c"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("e43b3f93-1b7a-48a9-829e-be9a7b99b75d"),
                            Amount = 30.0,
                            CategoryID = new Guid("9ad4ccf1-f72b-4fe2-9c76-e91cd01445d8"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Had a quick meal at Chick-fil-A before the flight.",
                            PaymentMode = 1,
                            RecipientID = new Guid("41f99a2a-3fed-4bec-bee2-465f46f933a5"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("84b7d10a-1f4d-4a19-afe9-f56b64f58d6e"),
                            Amount = 90.0,
                            CategoryID = new Guid("43a9d80e-581d-4639-9bcd-e062e7ac7176"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Purchased travel essentials at Burlington.",
                            PaymentMode = 1,
                            RecipientID = new Guid("7bb90da3-fee4-4a5b-8679-5d820e90ac3d"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("5f6182da-b9a5-4181-bf83-0dce3c009d9a"),
                            Amount = 150.0,
                            CategoryID = new Guid("8815ac70-1c20-4167-a045-964d819e195f"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Stocked up on groceries at Costco for the trip.",
                            PaymentMode = 1,
                            RecipientID = new Guid("c7ee15e0-5480-4544-b2d6-094ba5134ac7"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("d4c4089c-bf54-4825-96a5-7b444b849f2d"),
                            Amount = 200.0,
                            CategoryID = new Guid("a5c6d659-aaf2-495f-affc-015627059750"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Purchased a camera at Walmart for travel photos.",
                            PaymentMode = 1,
                            RecipientID = new Guid("1059d5f9-e4aa-4c06-8f35-e664b6215378"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("3d5c2a86-348a-43b4-bf3d-f1e5b4b2a75f"),
                            Amount = 150.0,
                            CategoryID = new Guid("8815ac70-1c20-4167-a045-964d819e195f"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Stocked up on groceries at Costco.",
                            PaymentMode = 1,
                            RecipientID = new Guid("c7ee15e0-5480-4544-b2d6-094ba5134ac7"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("5a9e1d88-ff26-4f55-a4e3-5c86f5291b79"),
                            Amount = 35.0,
                            CategoryID = new Guid("9ad4ccf1-f72b-4fe2-9c76-e91cd01445d8"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Enjoyed a family meal at Chick-fil-A.",
                            PaymentMode = 1,
                            RecipientID = new Guid("41f99a2a-3fed-4bec-bee2-465f46f933a5"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("c73c7f0e-cbf3-4c82-bdb9-8e3a8f9dffce"),
                            Amount = 200.0,
                            CategoryID = new Guid("43a9d80e-581d-4639-9bcd-e062e7ac7176"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Bought household items at Target.",
                            PaymentMode = 1,
                            RecipientID = new Guid("18884556-def7-499c-89df-09a8d95b62d0"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("29d6b144-c31c-4b0d-82db-ba042a60b8d0"),
                            Amount = 300.0,
                            CategoryID = new Guid("a5c6d659-aaf2-495f-affc-015627059750"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Purchased a new TV at BestBuy.",
                            PaymentMode = 1,
                            RecipientID = new Guid("1b5a7d64-2e25-48cd-8cd6-9587f6078ca5"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("6e9b83e6-3fb4-494c-bf61-b08d80f6db93"),
                            Amount = 12.0,
                            CategoryID = new Guid("9ad4ccf1-f72b-4fe2-9c76-e91cd01445d8"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Grabbed coffee and donuts from Dunkin'.",
                            PaymentMode = 1,
                            RecipientID = new Guid("dea8e720-e79c-4fc3-81fd-201befa9f904"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("0d5c78c6-f5e7-494f-83fb-6da06d1a50d2"),
                            Amount = 150.0,
                            CategoryID = new Guid("43a9d80e-581d-4639-9bcd-e062e7ac7176"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Bought clothes at Burlington.",
                            PaymentMode = 1,
                            RecipientID = new Guid("7bb90da3-fee4-4a5b-8679-5d820e90ac3d"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("7f8d6c5f-c0f8-4e8b-ac8c-75a5b67b5745"),
                            Amount = 250.0,
                            CategoryID = new Guid("a6d314d6-ab99-47f9-9b17-2c94f9f03086"),
                            CreditCardID = new Guid("75987053-7057-499b-bdf6-14ac41509853"),
                            Date = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Purchased a flight ticket to New York with Delta.",
                            PaymentMode = 1,
                            RecipientID = new Guid("7431dc59-2e5a-4863-a58b-05e17566e310"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("8f2d62f3-4a2c-42c2-be4d-bced4d26ed96"),
                            Amount = 70.0,
                            CategoryID = new Guid("8815ac70-1c20-4167-a045-964d819e195f"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Picked up groceries at Kroger.",
                            PaymentMode = 1,
                            RecipientID = new Guid("a53c4426-df1c-4325-8e52-4ea027a6e83e"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("6e86a8f7-87c5-4eb8-bc89-2acb5c03a03a"),
                            Amount = 180.0,
                            CategoryID = new Guid("a5c6d659-aaf2-495f-affc-015627059750"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Bought a new tablet at Walmart.",
                            PaymentMode = 1,
                            RecipientID = new Guid("1059d5f9-e4aa-4c06-8f35-e664b6215378"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("1db79274-33e6-4d7b-849c-44fcd745ebc7"),
                            Amount = 30.0,
                            CategoryID = new Guid("9ad4ccf1-f72b-4fe2-9c76-e91cd01445d8"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Had dinner at Panda Express.",
                            PaymentMode = 1,
                            RecipientID = new Guid("6ecf6c47-660e-4871-a6fc-9c17167a3b5d"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("3cff4d4c-5d44-43b4-98c4-8f0a378b8d64"),
                            Amount = 60.0,
                            CategoryID = new Guid("43a9d80e-581d-4639-9bcd-e062e7ac7176"),
                            CreditCardID = new Guid("cd4e4392-2fe6-4000-8f7b-d4c3885a0f7d"),
                            Date = new DateTime(2024, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Bought some spring clothes at H&M.",
                            PaymentMode = 1,
                            RecipientID = new Guid("fec14558-524a-46a1-ab0e-f8acfaf9ab49"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        },
                        new
                        {
                            TransactionID = new Guid("8f30a758-bb12-4e52-b73f-4f69c9b88c60"),
                            Amount = 25.0,
                            CategoryID = new Guid("9ad4ccf1-f72b-4fe2-9c76-e91cd01445d8"),
                            CreditCardID = new Guid("566863e0-cac1-427b-9f22-74519d3970d9"),
                            Date = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneralComments = "Enjoyed lunch at Burger King with friends.",
                            PaymentMode = 1,
                            RecipientID = new Guid("04848095-f6d3-489e-bfd2-92b09e039019"),
                            Status = false,
                            TransactionMode = 1,
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73")
                        });
                });

            modelBuilder.Entity("ExpenseTrackerWebAPI_Mk2.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = new Guid("8daa3821-3685-4299-a172-4bbf18929a73"),
                            Email = "admin@admin.com",
                            FirstName = "Admin",
                            LastName = "Nimda",
                            Password = "admin",
                            Status = false,
                            UserName = "admin"
                        },
                        new
                        {
                            UserID = new Guid("bd500ce6-dee1-4445-a214-410829db561b"),
                            Email = "john.reese@machine.com",
                            FirstName = "John",
                            LastName = "Reese",
                            Password = "john",
                            Status = false,
                            UserName = "John"
                        });
                });

            modelBuilder.Entity("ExpenseTrackerWebAPI_Mk2.Models.Bank", b =>
                {
                    b.HasOne("ExpenseTrackerWebAPI_Mk2.Models.User", "User")
                        .WithMany("Banks")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseTrackerWebAPI_Mk2.Models.CreditCard", b =>
                {
                    b.HasOne("ExpenseTrackerWebAPI_Mk2.Models.User", "User")
                        .WithMany("CreditCards")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseTrackerWebAPI_Mk2.Models.Transaction", b =>
                {
                    b.HasOne("ExpenseTrackerWebAPI_Mk2.Models.Bank", "Bank")
                        .WithMany("Transactions")
                        .HasForeignKey("BankID");

                    b.HasOne("ExpenseTrackerWebAPI_Mk2.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseTrackerWebAPI_Mk2.Models.CreditCard", "CreditCard")
                        .WithMany("Transactions")
                        .HasForeignKey("CreditCardID");

                    b.HasOne("ExpenseTrackerWebAPI_Mk2.Models.Recipient", "Recipient")
                        .WithMany("Transactions")
                        .HasForeignKey("RecipientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseTrackerWebAPI_Mk2.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Category");

                    b.Navigation("CreditCard");

                    b.Navigation("Recipient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseTrackerWebAPI_Mk2.Models.Bank", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ExpenseTrackerWebAPI_Mk2.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ExpenseTrackerWebAPI_Mk2.Models.CreditCard", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ExpenseTrackerWebAPI_Mk2.Models.Recipient", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ExpenseTrackerWebAPI_Mk2.Models.User", b =>
                {
                    b.Navigation("Banks");

                    b.Navigation("CreditCards");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
